language: node_js
node_js: stable
before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
script: npm test
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
env:
  global:
    secure: rMfZuwdutC0biRPNk+n4uhRCV2894dTNKfLv9rG8Pr5xcF8+2TNyY8IZxw3K7eeUR9R9NPmsEGrcGoPowRyYpwI7rN5UdgnmIG5N33McwYylPkNn6EqMhnjvFuGe0GgOTQGY1G0IPPfJvvdCvbUaqJKcjYUGvMMapKZTikmBEMKI5KZyMBZBLy1sC+Js6ITys4pSk2cETNyCZC6/2HaOh8plL+UJpcfoD3777JzRUP9iQOzs81BSaAi2FEygXk2dQtsPUr5Qv4085nJ2/kElu447feiMUUqp4gw52BxnLsv/H5b76VUIQvMwWtyFJ3iLhZDrOz11cOAtzL0zQx8kza8fJSKaTgwmeU50sBHQQUZ6lx+3gHd7lwjmGKoeAyO7ob8YH6wba22AZnFxWhYz9OzEVImB3JZZhF/J2ZEJgK+Ae1OGM4QtBWxzvN2hxanEWkCT2vgQgA9K8ZBQA6l/4uThKmgsJv0PkCZdNFQ+HQVsXuhBThBrceOs94rhxkFyxw+KOvQbhkS1Q/31aQcEKfgpE9FQcW29kqPBX7LywhwaepHUvdZehLx8c+L/dyv800SVkrsTimGC9tV8M2nVtiWVRoxBuTaVpnyz/JPnS7ijGXDR4TJtPeseppj/WycBrQOtCn/O6VamaWbeEGdOZCtHEJZKvIy7LCL89+GzlnY=
